[profile.default]
src = 'contracts'
test = 'test'
out = 'out'
libs = ['lib']
solc_version = '0.8.23'
optimizer = true
optimizer_runs = 200
remappings = [
    '@openzeppelin/=lib/openzeppelin-contracts/'
]

